Workaround for MSVC error C3493
I have to ignore the clang warning to work around the MSVC issue since
the library is for C++11 not >=C++14, where there is an available
workaround that doesn't involve ignoring a warning.